### ISSUE TITLE
Sync BP data with server

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#17]
## TODO:
- [x] Finalise data model for blood pressure
- [x] Add model, migrations, same validations as other models
- [x] Include mergeable concern, add mergeable test for BP
- [x] Write specs for blood pressure api
- [x] Implement sync: adding blood pressures, test this
- [x] Implement sync: retrieving blood pressures, test this

## Questions:
- [x] Do we compute risk level on mobile, store it, send it to server?
    - Assumption: we'll compute it on mobile, not send it to server

## Data Model, API spec

- id: uuid
- systolic: integer
- diastolic: integer
- created_at: timestamp
- updated_at: timestamp
- patient_id: uuid
- all are required
