### ISSUE TITLE
Admin can register User (backend)

### ISSUE THREAD

**Issue by dvenkatr** [simpledotorg/simple-android#43]
## Bugs

- [x] rename "password" to "PIN" so it's more obvious
- [x] restrict "full name" to alphabetic input
- [x] from a Facility's user list, there should be a "Create User" option

## User model
- id - UUID
- full_name - String
- phone_number - String [required, non empty]
- security_pin_hash - String

## Relationships
- [x] User belongs to one facility
- [x] User has recorded many blood pressures (updates the blood pressure model)

## Questions
- [x] Do we need to store the medical license number for the user?
  - assumption: since it doesn't appear in the screens for the MVP, we don't need this yet
- [x] Should we build a user interface to create or manage users?
  - yes
- [x] Should we build sync from device for user?
  - assumption: yes

## TODO
- [x] Create user model
- [x] Add factories for user
- [x] Build sync to device for user
- [x] Use rails scaffolding to generate views to CRUD users
- [x] use bcrypt to hash passwords

**Comment by deobald** [comment]
QA steps for @timcheadle and @terrycullen : 

1. Visit the integration server at http://13.127.130.247 

```
Side note: this test is done on the `integration` environment because the app is currently single-environment so that's where all your data will go... @ssrihari is working on environment-specific builds for Bitrise so we'll QA the app against a cleanroom QA server and similarly do webapp UI tests against the cleanroom QA environment as soon as we have an APK that points to it.
```

2. Log in with the username & password I've DM'd you

3. By default, you are taken to the `Facilities` UI at http://13.127.130.247/admin/facilities ... you can list, create, update, and delete Facilities here (if you find a bug in this step, please report it on the [Create Facility (#41) card](https://github.com/resolvetosavelives/redapp/issues/41).

4. Visit the User list at http://13.127.130.247/admin/users ... similarly, you can list, create, update, and delete Users here. This is the UI for User "Registration" (creation). Play this with UI and post bugs and comments on this card, tagging @ssrihari and @govindkrjoshi so they can quickly correct it.

**Comment by deobald** [comment]
@ssrihari @govindkrjoshi There's a small bug on `Facility#show`: Click a `User#edit` link from the Users list; you'll get a 404 because it accidentally links to `ProtocolDrug#edit`.

**Comment by terrycullen** [comment]
password can only be numbers?
name lets me just enter numbers (that seems like it isn't right)

**Comment by deobald** [comment]
@terrycullen Yes, "password" is probably the wrong label. This is the nurse's 4-digit PIN they will enter on the phone. Restricting `name` to numbers would definitely be wrong, but I'm not seeing that. The attached screenshot is a valid name, for example. Can you take a screenshot of the numbers-only name restriction you're seeing?

![screen shot 2018-06-15 at 11 15 39](https://user-images.githubusercontent.com/20282/41452056-a11e3fe6-708d-11e8-92b1-44631bb5ede3.png)

**Comment by terrycullen** [comment]
i meant that name allows there to just be numbers, not that it restricts to numbers ( should it just restrict to alpha).. and should we name password to something else?  i think daniel/tim can test that; maybe people will know that is their PIN @deobald

**Comment by deobald** [comment]
@terrycullen [copying from Slack] This web UI will only be used by you, Daniel, and Tim to begin with... hence its bare-bones nature. :) @ssrihari says he'll rename `password` to `PIN` in the form so it's self-explanatory. We can also restrict the `Full Name` field to alpha-only, if you feel that will prevent you folks from making typos.
