### ISSUE TITLE
As an Admin, I can manage the state protocol, and protocol drugs for facilities to decide what nurses can use in the mobile interface.

### ISSUE THREAD

**Issue by ssrihari** [simpledotorg/simple-android#9]
## Protocol Info
- [Protocol drug info for Punjab](https://slack-files.com/files-pri-safe/T0D2SCVU3-FAYF5NL9Z/punjab_-_a4_letter_hypertension_protocol.pdf?c=1527775464-3a2cdee1b997cb2042766e22fd240a04a0017261)
- [Thresholds](https://vitalstrat.slack.com/archives/CAJNUJDH6/p1526216645000053)

### Protocol
- id uuid
- name string
- follow_up_days integer

### ProtocolDrug
- id uuid
- name string
- dosage string
- protocol_id integer
- rxnorm_code string

### Facility
- protocol_id uuid

## Questions
- [x] Should we build a user interface to create or manage protocols and drugs?
  - Assumption: yes

## TODO
- [x] Create protocol and protocol drug models
- [x] Use rails scaffolding to generate views to CRUD protocols and protocol drugs
- [x] Add rake task to add Punjab's hypertension protocol
- [x] Build sync to device for protocol and protocol drugs

## Preview
![screen shot 2018-06-04 at 5 34 41 pm](https://user-images.githubusercontent.com/1003238/40916519-a05128a8-681d-11e8-8e35-1611aedb5625.png)
